const OFFICES = [
{"id":"1","name":"Prestige Family Dentistry","address":"4351 Cross Timbers #100","city":"Flower Mound","doctor":"Dr. Vincent DiRusso","tier":"hot","status":"Visited","contact":"Stacy (scheduler), Daniel (hygienist)","notes":"Dr. DiRusso & Dr. Patel are good friends (grew up in Michigan). Office tour; staff group photo. Market Street lunch delivered 7/9.","gift":"Market Street appreciation spread + refilled Patel cards","lastVisit":"2026-07-09","nextAction":"VIP — keep close; slate next touch","referralVolume":65,"topReferrer":true},
{"id":"2","name":"Active Dental","address":"1450 Long Prairie Rd Ste 160","city":"Flower Mound","doctor":"Dr. Jyothi Chodisetty","tier":"hot","status":"Visited","contact":"Suzette & Natasha (front)","notes":"HIGH opportunity. Hand out cards like candy. Appreciation lunch QR submitted 7/9. Never had an appreciation lunch before. (469) 293-2220","gift":"More Patel cards + appreciation lunch offer","lastVisit":"2026-07-09","nextAction":"Follow up on lunch order; lock L&L","referralVolume":40,"topReferrer":true},
{"id":"3","name":"Lifetime Dental of Flower Mound","address":"3208 Long Prairie Rd Ste A","city":"Flower Mound","doctor":"Dr. Dexter Dafney","tier":"hot","status":"Visited","contact":"Tyra (front)","notes":"#1 REFERRER (36/yr, high acceptance). Appreciation lunch QR submitted 7/9. Dr. Dafney was out — need to meet him in person.","gift":"Appreciation lunch offer (QR scanned)","lastVisit":"2026-07-09","nextAction":"Follow up on lunch order; catch Dr. Dafney in person","referralVolume":36,"topReferrer":true},
{"id":"4","name":"The Dental Studio","address":"2261 Olympia Dr Ste 300","city":"Flower Mound","doctor":"Dr. Yasi Sabour","tier":"hot","status":"Visited","contact":"Yori (insurance/treatment plans)","notes":"Recognized Nikki instantly. Luna Grill lunch ordered + paid 7/9. Yori picking up. 30-min visit, great rapport.","gift":"Appreciation lunch — Luna Grill (paid in person)","lastVisit":"2026-07-09","nextAction":"Confirm lunch delivery; strong L&L candidate"},
{"id":"5","name":"Ace Smile Dentistry","address":"200 Gerault Rd","city":"Flower Mound","doctor":"Dr. Prathyusha Mendu","tier":"hot","status":"Visited","contact":"Christina (assistant/front)","notes":"KEY OPPORTUNITY — actively searching for a perio office; current one (Las Colinas) too far, patients skip follow-ups. ROOT is 15 min away. Office of 4, open 3-4 yrs. Offered L&L + happy hour.","gift":"Mug quad + introduction folder + in-network sheet","lastVisit":"2026-07-09","nextAction":"Follow up THIS WEEK — lock L&L / happy hour — HIGH PRIORITY"},
{"id":"6","name":"Flower Mound Family Dentistry","address":"3401 Cross Timbers Rd Ste 100","city":"Flower Mound","doctor":"Dr. Gray / Dr. Nash (started 7/8)","tier":"hot","status":"Visited","contact":"Madison (front)","notes":"Pearl Street DSO. Dr. Gray strong referrer + Dr. Patel's friend. Met Dr. Nash on his first day 7/8 — gave Dr. Patel's cell for intro lunch. In office Wed/Thu.","gift":"Tiff's Treats welcome gift for Dr. Nash","lastVisit":"2026-07-08","nextAction":"Lock Patel-Nash lunch; drop referral sheets (owed)"},
{"id":"7","name":"Tenney Dental","address":"765 Cross Timbers Rd Ste 105","city":"Flower Mound","doctor":"Dr. Thomas Tenney","tier":"hot","status":"Visited","contact":"Krista / Lisa (front)","notes":"Dr. Tenney's summer packed — targeting FALL happy hour. Left Patel + NW cell to pass to Dr. Tenney.","gift":"Dirty soda box","lastVisit":"2026-07-08","nextAction":"Revisit fall — schedule happy hour"},
{"id":"8","name":"Capehart Dental","address":"850 Valley Ridge Blvd #112","city":"Lewisville","doctor":"Dr. Christopher Capehart","tier":"hot","status":"Visited","contact":"Gabby (front)","notes":"ROOT Scan Me emergency sign displayed front-and-center. Gave dirty-soda recipe tutorial. Caught after 3 prior closed attempts.","gift":"Dirty soda kit + Patel card + in-network sheet","lastVisit":"2026-07-07","nextAction":"Keep in-network top of mind; L&L candidate"},
{"id":"9","name":"Hebron Orthodontics","address":"1025 W Hebron Pkwy #122","city":"Flower Mound","doctor":"Dr. Vincent To","tier":"hot","status":"Visited","contact":"Christy (OM); 6 staff","notes":"They hand patients MULTIPLE perio-specialist cards — ROOT needs to be the preferred name. Admin day visit.","gift":"Dirty soda + materials","lastVisit":"2026-07-07","nextAction":"Stay top-of-mind; strong L&L target"},
{"id":"10","name":"Trinity Dental Care","address":"1000 W Rosemeade Pkwy #100","city":"Flower Mound","doctor":"","tier":"hot","status":"Visited","contact":"Kimberly (OM); 8 staff; (972) 394-5200","notes":"Currently refers perio to competitor Sigma. Very interested — HIGH opportunity. Unplanned drop-in 7/7.","gift":"Dirty soda box + introduction folder + in-network sheet","lastVisit":"2026-07-07","nextAction":"Displace Sigma — L&L / Dr. Patel intro"},
{"id":"11","name":"Ranchview Family Dentistry","address":"8300 N MacArthur Blvd #140, Irving","city":"Other","doctor":"","tier":"hot","status":"Visited","contact":"Madeline & Etzel (front); ~10 staff","notes":"Happy active referrer (online). Feedback: everything is perfect. Teased ROOT sleep-apnea/snoring service.","gift":"Dirty soda + Patel cards + insurance sheet","lastVisit":"2026-07-08","nextAction":"Maintain; follow up when sleep-apnea launches"},
{"id":"12","name":"Hillcrest Dental at Castle Hills","address":"","city":"Lewisville","doctor":"Dr. Namrata Shah","tier":"hot","status":"Visited","contact":"Astrid (front)","notes":"Uses monthly in-office traveling periodontist + places own implants. Dr. Patel & Dr. Shah haven't met. Offered L&L/happy hour.","gift":"Dirty soda kit + Patel cards + in-network + ROOT Med Spa discount + online referral access","lastVisit":"2026-07-06","nextAction":"Bring referral pads when order arrives; return with Tiff's Treats; pursue L&L"},
{"id":"13","name":"Northlake Dentistry","address":"1500 Commons Cir #100, Northlake","city":"Other","doctor":"Dr. Catherine Whinery","tier":"warm","status":"Visited","contact":"Kaylee (front, ~1 mo)","notes":"Per Amanda — ~$10K case. Grateful/excited; lunch order pending via QR.","gift":"Appreciation lunch offer (QR scanned)","lastVisit":"2026-07-09","nextAction":"Follow up when lunch order submitted"},
{"id":"14","name":"Family Smiles Dental Group","address":"2650 Firewheel","city":"Flower Mound","doctor":"Dr. Nicole Miller / Dr. Jenifer Nichols","tier":"hot","status":"Visited","contact":"Minnie","notes":"Top Referral | 6/22/26 snack box + ref pads + cards; Minnie","gift":"Snack box + ref pads + cards","lastVisit":"2026-06-22","nextAction":"Slate appreciation lunch"},
{"id":"15","name":"Cross Timbers Dental","address":"2240 Cross Timbers Rd Ste 100","city":"Flower Mound","doctor":"Dr. Barry Buschel / Dr. Pamela Medici / Dr. Brad Revering","tier":"hot","status":"Visited","contact":"Betsy & Sonya","notes":"Top Referral | veggie tray + cards; Betsy & Sonya - 6/26/26","gift":"Veggie tray + cards","lastVisit":"2026-06-26","nextAction":"Slate appreciation lunch"},
{"id":"16","name":"214 Dental Arts","address":"4320 Windsor Centre Trail Ste 400","city":"Flower Mound","doctor":"Dr. Leena Ponnapali","tier":"hot","status":"Visited","contact":"Emily","notes":"Top Referral | 6/23/26 snack basket; Emily - uses online refs","gift":"Snack basket","lastVisit":"2026-06-23","nextAction":"Slate appreciation lunch"},
{"id":"17","name":"Dental Depot - Highland Village","address":"2460 FM 407","city":"Highland Village","doctor":"Dr. Neil Patel / Dr. Michael Wing / Dr. Tony Zhang","tier":"hot","status":"Visited","contact":"Eboni (mgr)","notes":"Top Referral | 6/22/26 snack box + ref pads + cards","gift":"Snack box + ref pads + cards","lastVisit":"2026-06-22","nextAction":"Slate appreciation lunch"},
{"id":"18","name":"Prentice Dental","address":"2900 Long Prairie Rd Ste D","city":"Flower Mound","doctor":"Dr. Joshua Prentice","tier":"hot","status":"Visited","contact":"Esi","notes":"Top Referral | healthy snack box; Esi - online refs - 6/30/26","gift":"Healthy snack box","lastVisit":"2026-06-30","nextAction":"Slate appreciation lunch"},
{"id":"19","name":"Flower Mound Dental","address":"2021 Justin Rd Ste 119","city":"Flower Mound","doctor":"Dr. Bellingham","tier":"hot","status":"Visited","contact":"","notes":"Top Referral | Tiff's Treats + cards - 6/24/26","gift":"Tiff's Treats + cards","lastVisit":"2026-06-24","nextAction":"Slate appreciation lunch"},
{"id":"20","name":"Jordan Carl DMD","address":"105 Kathryn Dr Ste A","city":"Lewisville","doctor":"Dr. Jordan Carl","tier":"hot","status":"Visited","contact":"Nancy","notes":"Top Referral | snack box + insurance + cards; Nancy - 6/29/26","gift":"Snack box + insurance + cards","lastVisit":"2026-06-29","nextAction":"Slate appreciation lunch"},
{"id":"21","name":"Dawson Family Dentistry","address":"1278 Justin Rd Ste 108","city":"Lewisville","doctor":"Dr. Christina Dawson","tier":"hot","status":"Visited","contact":"Donna","notes":"Top Referral | dirty soda box + in-network; Donna - 7/1/26","gift":"Dirty soda box + in-network","lastVisit":"2026-07-01","nextAction":"Follow up"},
{"id":"22","name":"Cheer Dental","address":"","city":"Lewisville","doctor":"Dr. Patricia Guerra-Hirji","tier":"hot","status":"Visited","contact":"Rita","notes":"Top Referral | 6/22/26 snack box + ref pads + cards; Rita","gift":"Snack box + ref pads + cards","lastVisit":"2026-06-22","nextAction":"Slate appreciation lunch"},
{"id":"23","name":"Highland Village Smile Studio","address":"1401 Shoal Creek","city":"Highland Village","doctor":"Dr. Nicole Richardson","tier":"hot","status":"Visited","contact":"","notes":"Top Referral | McAlister's thank-you lunch delivered 6/30/26","gift":"McAlister's lunch","lastVisit":"2026-06-30","nextAction":"Follow up"},
{"id":"24","name":"Highland Village Family Dentistry","address":"2600 Village","city":"Highland Village","doctor":"Dr. Mark Wagner / Dr. Jackson Fuller","tier":"hot","status":"Visited","contact":"Jennifer","notes":"Top Referral | healthy box; Jennifer - refers online - 6/29/26","gift":"Healthy box","lastVisit":"2026-06-29","nextAction":"Slate appreciation lunch"},
{"id":"25","name":"Campbell and Williams Family Dentistry","address":"","city":"Highland Village","doctor":"Dr. David Campbell / Dr. Mark Williams","tier":"hot","status":"Visited","contact":"Sulee","notes":"Top Referral | dirty soda box + in-network; Sulee - 7/1/26 (owes referral pads)","gift":"Dirty soda box + in-network","lastVisit":"2026-07-01","nextAction":"Drop referral pads when order arrives"},
{"id":"26","name":"Endodontic Excellence (Rajiv Patel)","address":"4421 Long Prairie Rd","city":"Flower Mound","doctor":"Dr. Rajiv Patel","tier":"hot","status":"Visited","contact":"Cassie","notes":"Dr. Patel's friend / study-club endo. Top Referral. Visited 7/6 dirty soda.","gift":"Dirty soda kit","lastVisit":"2026-07-06","nextAction":"Keep warm"},
{"id":"27","name":"Smiles & Beyond Dental","address":"250 Gerault Rd Ste 150","city":"Flower Mound","doctor":"Dr. Ira Mims","tier":"warm","status":"Visited","contact":"","notes":"Great doctor rapport; sends extractions incl. tough cases; online referrals. Dr. Patel has relationship.","gift":"Dirty soda box","lastVisit":"2026-07-06","nextAction":"Keep warm; L&L / relationship candidate"},
{"id":"28","name":"Smiles Family Dental","address":"","city":"Flower Mound","doctor":"Dr. Angelie Zamora / Dr. Ruasha Shrestha","tier":"warm","status":"Visited","contact":"Alta (front); Patrick (OM)","notes":"Have referred to ROOT before. Offered L&L; pitched connecting Dr. Patel + Dr. Zamora.","gift":"Dirty soda kit + in-network sheet","lastVisit":"2026-07-06","nextAction":"Referral-forms drop-back; ask for Patrick; L&L follow-up"},
{"id":"29","name":"Titensor Dental","address":"","city":"Flower Mound","doctor":"Dr. Brett Titensor / Dr. Joseph Mann","tier":"warm","status":"Visited","contact":"Tracey (front)","notes":"Relocating late July / early August. Excited for new expanded space.","gift":"Dirty soda box","lastVisit":"2026-07-06","nextAction":"Revisit after move — congratulate + build relationship"},
{"id":"30","name":"ACE Dental - Lewisville","address":"713 Hebron Pkwy #216","city":"Lewisville","doctor":"Dr. Shailaja Reddy","tier":"warm","status":"Visited","contact":"Amanda (front)","notes":"4-person team; closed Wed/Sun. Educated on We Save Teeth. Offered L&L.","gift":"In-network sheet + Patel cards","lastVisit":"2026-07-07","nextAction":"L&L candidate; bring dirty soda + ref pads next round"},
{"id":"31","name":"Prairie Creek Dental","address":"457 W Main St","city":"Lewisville","doctor":"Dr. Gregory Holbrook","tier":"warm","status":"Visited","contact":"Gabby (front); 5 staff","notes":"First touch 7/8. Keeps cases in-house (low perio volume). Opened two-way GD relationship. Interested in in-network.","gift":"Dirty soda box + Patel cards","lastVisit":"2026-07-08","nextAction":"Nurture as two-way GD outlet"},
{"id":"32","name":"Lantana Family Dentistry","address":"4110 FM 407 #150","city":"Other","doctor":"Dr. Cleveland","tier":"warm","status":"Visited","contact":"Ashley (front)","notes":"Refers perio elsewhere; mutual patients. Positioned ROOT as urgent/same-day option. Closes 1pm Wednesdays.","gift":"Dirty soda gift + in-network sheet","lastVisit":"2026-07-08","nextAction":"Stay on radar as urgent-case option"},
{"id":"33","name":"Oval Dental","address":"4471 Long Prairie Ste 300","city":"Flower Mound","doctor":"Dr. Virgil Vacarean","tier":"warm","status":"Visited","contact":"Stacey (front)","notes":"Not currently referring; office busy. Attempted 6/23 — closed. Visited 7/6.","gift":"Patel cards + in-network sheet","lastVisit":"2026-07-06","nextAction":"Circle back to learn referral flow"},
{"id":"34","name":"Stokes Orthodontics","address":"6011 Morriss Rd Ste 100A","city":"Flower Mound","doctor":"Dr. Lisa Stokes","tier":"warm","status":"Visited","contact":"Stacey (front)","notes":"Not currently referring; brief intro. Closed 6/24; visited 7/6.","gift":"Patel cards + in-network sheet","lastVisit":"2026-07-06","nextAction":"Build relationship; learn where they refer"},
{"id":"35","name":"Northstar Dentistry","address":"","city":"Lewisville","doctor":"","tier":"warm","status":"Visited","contact":"Julia","notes":"Owes referral pads — on drop-back list.","gift":"Dirty soda box + in-network","lastVisit":"2026-07-01","nextAction":"Drop ref pads when order arrives"},
{"id":"36","name":"Wakefield Family & Cosmetic Dentistry","address":"326 S Edmonds","city":"Lewisville","doctor":"Dr. Brian Wakefield","tier":"warm","status":"Visited","contact":"Lisa","notes":"Reactivation | dirty soda box + in-network; Lisa - PAPER refs - 7/1/26","gift":"Dirty soda box + in-network","lastVisit":"2026-07-01","nextAction":"Drop referral pads when order arrives"},
{"id":"37","name":"Isla Dental","address":"","city":"Lewisville","doctor":"Dr. Jason Bacon","tier":"warm","status":"Visited","contact":"Alex","notes":"Requested referral forms Tue/Wed. On drop-back list.","gift":"Snack box","lastVisit":"2026-06-29","nextAction":"Drop referral forms when order arrives"},
{"id":"38","name":"Cafe Smile Studio","address":"2330 Justin Rd #300","city":"Highland Village","doctor":"Dr. Neha Gupta","tier":"warm","status":"Visited","contact":"Bryan","notes":"New Doctor | dirty soda box + in-network; Bryan - 7/1/26","gift":"Dirty soda box + in-network","lastVisit":"2026-07-01","nextAction":"Follow up"},
{"id":"39","name":"Village Parkway Dental","address":"2250 Village Pkwy","city":"Highland Village","doctor":"Dr. Shane Mason","tier":"warm","status":"Visited","contact":"Reagan","notes":"41+ | dirty soda box + in-network; Reagan - 7/1/26","gift":"Dirty soda box + in-network","lastVisit":"2026-07-01","nextAction":"Follow up"},
{"id":"40","name":"Highland Village Dental","address":"","city":"Highland Village","doctor":"Dr. Audrey S.","tier":"warm","status":"Visited","contact":"Ashley","notes":"41+ | dirty soda box + in-network; Ashley - happy hour - 7/1/26","gift":"Dirty soda box + in-network","lastVisit":"2026-07-01","nextAction":"Follow up"},
{"id":"41","name":"Gronberg & Sugay Dental","address":"","city":"Highland Village","doctor":"Dr. Gronberg & Dr. Sugay","tier":"warm","status":"Visited","contact":"Melissa","notes":"41+ | healthy snacks; Melissa - intro - 6/29/26","gift":"Healthy snacks","lastVisit":"2026-06-29","nextAction":"Follow up"},
{"id":"42","name":"Dental Care 4 Kids","address":"","city":"Flower Mound","doctor":"Dr. Melissa Waters","tier":"warm","status":"Visited","contact":"Shannon","notes":"Reactivation | ref pads + cards + Tiff's Treats; Shannon - 6/23/26","gift":"Ref pads + cards + Tiff's Treats","lastVisit":"2026-06-23","nextAction":"Follow up"},
{"id":"43","name":"Stasny Dental","address":"101 Long Prairie Rd Ste 752","city":"Flower Mound","doctor":"Dr. Robert Stasny","tier":"warm","status":"Visited","contact":"Taneka","notes":"Reactivation | veggie tray + cards; Taneka - 6/26/26","gift":"Veggie tray + cards","lastVisit":"2026-06-26","nextAction":"Follow up"},
{"id":"44","name":"Atelier Dental","address":"3020 Broadmoor Ln Ste 100","city":"Flower Mound","doctor":"Dr. Alex Seok Jun Lee","tier":"warm","status":"Visited","contact":"Levy","notes":"New Office | snack box + cards + in-network; Levy - 6/30/26","gift":"Snack box + cards + in-network","lastVisit":"2026-06-30","nextAction":"Follow up"},
{"id":"45","name":"Dental Depot Lewisville","address":"1260 W Main","city":"Lewisville","doctor":"","tier":"warm","status":"Visited","contact":"Lucas (mgr)","notes":"6/22/26 snack box + ref pads + cards; Lucas","gift":"Snack box + ref pads + cards","lastVisit":"2026-06-22","nextAction":"Slate appreciation lunch"},
{"id":"46","name":"Dazzle Dental","address":"","city":"Flower Mound","doctor":"","tier":"warm","status":"Visited","contact":"Hon","notes":"41+ | veggie tray + cards; Hon - offered L&L - 6/26/26","gift":"Veggie tray + cards","lastVisit":"2026-06-26","nextAction":"Lock in L&L"},
{"id":"47","name":"Today Dental of Flower Mound","address":"2840 Flower Mound Rd","city":"Flower Mound","doctor":"Dr. Greg Peterson","tier":"warm","status":"Visited","contact":"Brittany (mgr)","notes":"41+ | healthy basket; Brittany - planted L&L - 6/30/26","gift":"Healthy basket","lastVisit":"2026-06-30","nextAction":"Lock in L&L"},
{"id":"48","name":"Smiles By Design","address":"3301 Long Prairie Rd Ste 110","city":"Flower Mound","doctor":"Dr. Sandra Sieber","tier":"warm","status":"Visited","contact":"Cheryl (mgr)","notes":"Reactivation | veggie tray + cards; Cheryl offered L&L - 6/26/26","gift":"Veggie tray + cards","lastVisit":"2026-06-26","nextAction":"Lock in L&L"},
{"id":"49","name":"Towne View Dental Care","address":"1900 Long Prairie Rd Ste 132","city":"Flower Mound","doctor":"Dr. Dhaval Patel","tier":"warm","status":"Visited","contact":"","notes":"Reactivation | snack box + in-network; met Dr. Dhaval Patel - 6/30/26","gift":"Snack box + in-network","lastVisit":"2026-06-30","nextAction":"Follow up"},
{"id":"50","name":"Clove Family Dental","address":"4271 Esplanade Pl Ste 120","city":"Flower Mound","doctor":"Dr. Puja Patel","tier":"warm","status":"Visited","contact":"Jazz & Lexis","notes":"Reactivation | veggie tray + cards; Jazz & Lexis - 6/26/26","gift":"Veggie tray + cards","lastVisit":"2026-06-26","nextAction":"Follow up"},
{"id":"51","name":"Fountain Park Dental","address":"1001 Long Prairie Rd Ste 100","city":"Flower Mound","doctor":"Dr. Girish Chaudari","tier":"warm","status":"Visited","contact":"","notes":"41+ | replaced outdated referral forms - 6/23/26","gift":"Referral forms","lastVisit":"2026-06-23","nextAction":"Follow up"},
{"id":"52","name":"Hal Stewart DDS","address":"6011 Morriss","city":"Flower Mound","doctor":"Dr. Hal Stewart & Dr. Adriana Corredor-Stewart","tier":"warm","status":"Visited","contact":"MaryAnn","notes":"New Office | snack box + cards + in-network; MaryAnn - 6/29/26","gift":"Snack box + cards + in-network","lastVisit":"2026-06-29","nextAction":"Follow up"},
{"id":"53","name":"Genesis Dental","address":"","city":"Flower Mound","doctor":"","tier":"warm","status":"Visited","contact":"","notes":"41+ | healthy basket + cards; front desk unattended - 6/29/26","gift":"Healthy basket + cards","lastVisit":"2026-06-29","nextAction":"Return visit"},
{"id":"54","name":"Bailey Dental","address":"","city":"Flower Mound","doctor":"Dr. Luke Bailey & Dr. Brittany Spruiell","tier":"warm","status":"Visited","contact":"Amy","notes":"41+ | Patel cards + Med Spa card; Amy - 6/26/26","gift":"Patel cards + Med Spa card","lastVisit":"2026-06-26","nextAction":"Follow up"},
{"id":"55","name":"Family Dental Care","address":"3051 Churchill Dr #200","city":"Flower Mound","doctor":"Dr. Amin Ashfour","tier":"warm","status":"Visited","contact":"Janet","notes":"41+ | healthy snack basket + in-network; Janet - 6/30/26","gift":"Healthy snack basket + in-network","lastVisit":"2026-06-30","nextAction":"Follow up"},
{"id":"56","name":"Healthy Smiles","address":"1050 Flower Mound Rd Ste 180","city":"Flower Mound","doctor":"Dr. Varsha Kulkarni","tier":"warm","status":"Visited","contact":"Nenu","notes":"41+ | veggie tray + cards; Nenu - 6/26/26","gift":"Veggie tray + cards","lastVisit":"2026-06-26","nextAction":"Follow up"},
{"id":"57","name":"Razz Orthodontics","address":"5401 Long Prairie Rd Ste 300","city":"Flower Mound","doctor":"","tier":"warm","status":"Visited","contact":"Nevaeh","notes":"21-40 | veggie tray + cards; Nevaeh - 6/26/26","gift":"Veggie tray + cards","lastVisit":"2026-06-26","nextAction":"Follow up"},
{"id":"58","name":"Brite Smiles Dentistry","address":"","city":"Flower Mound","doctor":"Dr. Salguti","tier":"warm","status":"Visited","contact":"Amber","notes":"41+ | veggie tray + cards; Amber - missed Dr. Salguti - 6/26/26","gift":"Veggie tray + cards","lastVisit":"2026-06-26","nextAction":"Follow up"},
{"id":"59","name":"FloMo Dental","address":"","city":"Flower Mound","doctor":"Dr. Sowjanya Gunukula / Dr. Dal Ho Lee","tier":"warm","status":"Visited","contact":"","notes":"41+ | Tiff's Treats + cards - 6/24/26","gift":"Tiff's Treats + cards","lastVisit":"2026-06-24","nextAction":"Follow up"},
{"id":"60","name":"Bridlewood Dental of Flower Mound","address":"","city":"Flower Mound","doctor":"Dr. Rodger Song","tier":"warm","status":"Visited","contact":"","notes":"41+ | Tiff's Treats + referral forms - 6/24/26","gift":"Tiff's Treats + referral forms","lastVisit":"2026-06-24","nextAction":"Follow up"},
{"id":"61","name":"Flower Mound Orthodontics","address":"2845 Morriss Rd","city":"Flower Mound","doctor":"Dr. Wayne Sankey","tier":"warm","status":"Visited","contact":"","notes":"Reactivation | Tiff's Treats + cards - 6/24/26","gift":"Tiff's Treats + cards","lastVisit":"2026-06-24","nextAction":"Follow up"},
{"id":"62","name":"Flower Mound Dentistry DiVine","address":"2200 Morriss Rd","city":"Flower Mound","doctor":"Kiamesha McClellan","tier":"warm","status":"Visited","contact":"","notes":"Reactivation | Tiff's Treats + cards - 6/24/26","gift":"Tiff's Treats + cards","lastVisit":"2026-06-24","nextAction":"Follow up"},
{"id":"63","name":"Brad Duren Dentistry","address":"4030 Justin Rd","city":"Flower Mound","doctor":"","tier":"warm","status":"Visited","contact":"Rhonda & Debbie","notes":"Reactivation | healthy box + cards + in-network; CFOP concern","gift":"Healthy box + cards + in-network","lastVisit":"2026-06-29","nextAction":"Confirm CFOP/insurance follow-up"},
{"id":"64","name":"Smiles for Life Orthodontics","address":"4030 Justin Rd Ste 100","city":"Flower Mound","doctor":"Dr. Irelia Machado","tier":"warm","status":"Visited","contact":"Brooke","notes":"Reactivation | snack box + insurance; Brooke - intro - 6/29/26","gift":"Snack box + insurance","lastVisit":"2026-06-29","nextAction":"Follow up"},
{"id":"65","name":"Prestige Family Dentistry (Bryant Nguyen / Jenny Shin)","address":"","city":"Flower Mound","doctor":"Dr. Bryant Nguyen / Dr. Jenny Shin","tier":"hot","status":"Visited","contact":"","notes":"Top Referral | Starbucks drinks 5/26/26","gift":"Starbucks drinks","lastVisit":"2026-05-26","nextAction":"Follow up — overdue"},
{"id":"66","name":"Endodontic Excellence (Jeannie Wang)","address":"4421 Long Prairie","city":"Flower Mound","doctor":"Dr. Jeannie Wang","tier":"warm","status":"Visited","contact":"","notes":"NOTE: Dr. Wang LEFT the practice. Confirm new doctor status.","gift":"","lastVisit":"2025-12-22","nextAction":"Confirm new doctor status"},
{"id":"67","name":"Aaron Crossley DDS","address":"","city":"Flower Mound","doctor":"Dr. Aaron Crossley","tier":"warm","status":"Visited","contact":"","notes":"20-40 | Monthly Gift veggie tray + Patel cards - 6/26/26","gift":"Veggie tray + Patel cards","lastVisit":"2026-06-26","nextAction":"Follow up"},
{"id":"68","name":"Hebron Orthodontics (Carrollton)","address":"1025 W Hebron Pkwy #122","city":"Other","doctor":"Dr. Vincent To","tier":"warm","status":"Visited","contact":"Christy (OM)","notes":"6 staff; admin day. Hands patients multiple perio cards to choose from.","gift":"Dirty soda box + materials","lastVisit":"2026-07-07","nextAction":"L&L; become preferred perio recommendation"},
{"id":"69","name":"Glorious Smiles","address":"500 Flower Mound Rd","city":"Flower Mound","doctor":"Dr. Gloria Lopez Bhushan","tier":"warm","status":"New - not visited","contact":"","notes":"Reactivation — not yet visited","gift":"","lastVisit":null,"nextAction":"First visit"},
{"id":"70","name":"Irving Kids Dentist (Elizabeth Joseph)","address":"3108 N MacArthur Blvd","city":"Other","doctor":"Dr. Elizabeth Joseph","tier":"warm","status":"New - not visited","contact":"","notes":"Reactivation — Irving","gift":"","lastVisit":null,"nextAction":"First visit"},
{"id":"71","name":"Baylor Scott & White Family Medicine","address":"","city":"Flower Mound","doctor":"Dr. Melinda Bautista Balarbar","tier":"warm","status":"New - not visited","contact":"","notes":"New Doctor","gift":"","lastVisit":null,"nextAction":"First intro"},
{"id":"72","name":"Parkview Dental","address":"625 Parkview Dr Ste 101, Trophy Club","city":"Other","doctor":"Dr. Linda Dinh","tier":"warm","status":"Visited","contact":"","notes":"New Office | 2/3/26 - Alyse","gift":"","lastVisit":"2026-02-03","nextAction":"Follow up — overdue"},
{"id":"73","name":"Rodeo Dental - Irving","address":"3559 N Belt Line Rd","city":"Other","doctor":"Dr. Madhulika Yemba","tier":"warm","status":"Visited","contact":"","notes":"21-40 | Alyse dropped insurance + gift 3/9/26 - Irving","gift":"Insurance + gift","lastVisit":"2026-03-09","nextAction":"Follow up"},
{"id":"74","name":"Ranchview Family Dentistry (Irving)","address":"8300 N MacArthur Blvd #140","city":"Other","doctor":"","tier":"cold","status":"Visited","contact":"","notes":"Outside core FM territory. Re-establish.","gift":"","lastVisit":"2026-05-28","nextAction":"Re-establish"},
{"id":"75","name":"Ace Smile Dentistry (prev closed)","address":"200 Gerault Rd","city":"Flower Mound","doctor":"Dr. Prathyusha Mendu","tier":"cold","status":"Attempted/Closed","contact":"","notes":"Closed 7/7 and 7/8 — finally caught 7/9.","gift":"","lastVisit":"2026-07-07","nextAction":"Caught 7/9 — see Ace Smile entry"},
{"id":"76","name":"Texas Center for Oral Surgery & Dental Implants","address":"651 Cross Timbers Rd #103","city":"Flower Mound","doctor":"Dr. Vickers + team","tier":"hot","status":"Do Not Target","contact":"","notes":"CO-LOCATED in ROOT FM building. In-house touch only — not a route stop. Refers ~6/yr via Dr. Vickers.","gift":"","lastVisit":null,"nextAction":"Easy in-building touch when at ROOT FM"},
{"id":"77","name":"Las Colinas Dental Care","address":"3203 N MacArthur Blvd, Irving","city":"Other","doctor":"Dr. Jeff Borgman","tier":"cold","status":"Do Not Target","contact":"","notes":"DR. PATEL DOES NOT WANT TO WORK WITH THIS OFFICE (per 7/8/26). Flag in Referral Lab.","gift":"","lastVisit":null,"nextAction":"DO NOT TARGET"},
{"id":"78","name":"Texas Dental Solutions / Associates in PIE","address":"1005 Long Prairie Rd #100","city":"Flower Mound","doctor":"Associates in PIE","tier":"cold","status":"Do Not Target","contact":"","notes":"Now a periodontal/endodontic SPECIALTY office — competitor. Not a referral target.","gift":"","lastVisit":"2026-07-07","nextAction":"Remove from outreach"},
{"id":"79","name":"My Highland Village Dentist","address":"3120 Justin Rd Ste B","city":"Highland Village","doctor":"Dr. Fred & Dr. Faraz","tier":"cold","status":"Do Not Target","contact":"","notes":"PERMANENTLY CLOSED confirmed 7/8/26. Remove from routes; flag in Referral Lab.","gift":"","lastVisit":null,"nextAction":"Remove from routes — CLOSED"},
{"id":"80","name":"Shine and Sparkle Dentistry","address":"6505 W Park Blvd #132","city":"Other","doctor":"Dr. Mujibunnisa Shaik","tier":"warm","status":"New - not visited","contact":"","notes":"New Office - Plano","gift":"","lastVisit":null,"nextAction":"First intro"}
];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  if (req.method === 'GET') return res.status(200).json(OFFICES);
  if (req.method === 'POST') {
    const o = { ...req.body, id: 'o' + Date.now() };
    OFFICES.push(o);
    return res.status(200).json(o);
  }
  if (req.method === 'PATCH') {
    const idx = OFFICES.findIndex(o => o.id === req.body.id);
    if (idx >= 0) Object.assign(OFFICES[idx], req.body);
    return res.status(200).json(OFFICES[idx] || {});
  }
  if (req.method === 'DELETE') {
    const idx = OFFICES.findIndex(o => o.id === req.body.id);
    if (idx >= 0) OFFICES.splice(idx, 1);
    return res.status(200).json({ success: true });
  }
}
